name: termstyle
description: A small library to make writing command-line apps more fun. Bringing emojis and colors to your console!
version: 1.9.0
homepage: https://github.com/angeldollface/termstyle
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  pedantic: ^1.11.0
